### ISSUE TITLE
Right click nothing happens W10 64-bit

### ISSUE THREAD

**Issue by Ragshnak** [acidhax/chromecast-audio-stream#31]
Downloaded the program and it just gives me an icon in the tray that you cannot right click, if you do nothing happens.

**Comment by KZNcode** [comment]
Same here.

**Comment by KZNcode** [comment]
fixed after killing the program and restarting.

**Comment by Ragshnak** [comment]
bbuds fix does not work for me, i have even restarted the computer and it still does not work.

**Comment by spoctoss** [comment]
same issue here, tried bbuds suggestion no luck.

**Comment by lolouk44** [comment]
Same here. Having to close the app, and restart it.

**Comment by Bidley** [comment]
Same problem here. Closing and restarting does nothing, running as admin does nothing, can't right click on the icon in the tray.

**Comment by matbeedotcom** [comment]
Does installing this fix the problem? https://github.com/acidhax/chromecast-audio-stream/releases/download/0.2.5/BonjourPSSetup.exe

_restart_

**Comment by matbeedotcom** [comment]
Fixing the issue.

**Comment by Ragshnak** [comment]
I installed BonjourPSSetup.exe and followed the wizard. After i installed it i restarted (made sure the program wasn't still running with the task manager) the audio-cast program and then started it again with the audio-cast.exe.

**Comment by Gionames** [comment]
After installing Bonjour, I managed for the first time to stream sound from pc to Chromecast. But on a Surface Pro 4 with Intel i5 there's a lag of 5 seconds

**Comment by Ragshnak** [comment]
I finally got it working on my windows 10 today by running it in windows 8 compatability mode. Not sure if this is a normal bug or not, but when i want to disconnect (clicking the name of my chromecast and uncheck it) from the chromecast audio it just reconnects instead and the "checkbox" is gone. Hope this will help others as well just to get it working. Feel stupid that i didn't test this before...
